post_install() {
	# lpr
	/opt/brother/Printers/dcpj774dw/inf/setupPrintcapij dcpj774dw -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj774dw/cupswrapper/cupswrapperdcpj774dw
	
	systemctl restart org.cups.cupsd.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj774dw/inf/setupPrintcapij dcpj774dw -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj774dw/cupswrapper/cupswrapperdcpj774dw -e
}

op=$1
shift

$op "$@"

